image: nexus.riaint.ee:8500/node:16.15.1-slim

stages:
  - publish

publish:
  stage: publish
  script:
    - npm i
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - PACKAGE_VERSION=${NPM_PACKAGE_VERSION}-${CI_JOB_ID}
    - npm version ${PACKAGE_VERSION} --no-git-tag-version && cd projects/ria/${COMPONENT_NAME} && npm version ${PACKAGE_VERSION} --no-git-tag-version && cd ../../../
    - npm run build-prod @ria/stateportal-form-generator

    - echo "registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "_authToken=${CI_DEPLOY_PASSWORD}">>.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_DEPLOY_PASSWORD}">>.npmrc
    - npm config list
    - npm publish dist/ria/stateportal-form-generator
